config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[index new create show]
  # ネストしたルーティング（shallowルーティング）
  resources :posts, shallow: true do
    # searchアクションのルーティング
    collection do
      get 'search'
    end
    resources :comments, only: %i[create edit update destroy]
  end
  # like
  # いいね機能のルーティング
  resources :likes, only: %i[create destroy]
  # follow_unfollow機能のルーティング
  resources :relationships, only: %i[create destroy]
  # acitivityのルーティング
  resources :activities, only: [] do
    patch :read, on: :member
  end
  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
    mount Sidekiq::Web, at: '/sidekiq'
  end
  root      'posts#index'
  get       '/login'    =>  'sessions#new'
  post      '/login'    =>  'sessions#create'
  delete    '/logout'   =>  'sessions#destroy'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  content    :text(65535)      not null
#  pictures   :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  # ユーザーとの関連付け
  belongs_to :user
  # いいねとの関連付け
  has_many :likes, dependent: :destroy
  # いいねされたユーザーとの関連付け
  has_many :liked_user, through: :likes, source: :user
  # コメントとの関連付け
  has_many :comments, dependent: :destroy
  validates :pictures, presence: true
  validates :content, { presence: true, length: { maximum: 1000 } }
  # テキスト型のカラムに配列を格納するために、形式をjson型にしている
  serialize :pictures, JSON
  # 画像を複数枚保存するので、mount_uploaderはmount_uploadersとなる
  mount_uploaders :pictures, PictureUploader

  # 共通のクエリの処理を設定し、それをメソッド（()の中は引数）のように使えるようにする
  scope :content_contain, ->(word) { where('content LIKE ?', "%#{word}%") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new create edit update destroy]

  def index
    @posts = if current_user
               # ログインユーザー自身と、フォローしているユーザーの投稿
               current_user.feed.includes(:user).order(created_at: :desc).page(params[:page])
             else
               # N+1問題、ページネーションに対応
               Post.includes(:user).order(created_at: :desc).page(params[:page])
             end

    # ユーザーを登録が新しい順に５人
    @users = User.order(created_at: :desc).limit(5)
  end

  def new
    @post = Post.new
  end

  def create
    # postに現在のユーザーの情報を付与している
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました'
      redirect_to posts_path
    else
      flash[:danger] = '投稿に失敗しました'
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
    # コメント表示のため
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    # コメント作成フォームのため
    @comment = Comment.new
  end

  def edit
    # postが現在ログインしているユーザーのpostであるときのみ編集できる
    @post = current_user.posts.find(params[:id])
  end

  def update
    # postが現在ログインしているユーザーのpostであるときのみ編集できる
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      flash[:success] = '投稿を更新しました'
      redirect_to posts_path
    else
      flash[:danger] = '投稿の更新に失敗しました'
      render 'new'
    end
  end

  def destroy
    # postが現在ログインしているユーザーのpostであるときのみ削除できる
    @post = current_user.posts.find(params[:id])
    @post.destroy
    flash[:success] = '投稿を削除しました'
    redirect_to posts_path
  end

  def search
    @posts = @search_form.search.includes(:user).page(params[:page])
  end

  private

  def post_params
    # picturesは配列でパラメータを受け取りたい
    params.require(:post).permit(:content, pictures: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
= form_with model: post, local: true, id: 'posts_form' do |f|
  = render 'shared/error_messages', object: post
  .form-group
    = f.label :pictures
    = f.file_field :pictures, multiple: true, class: 'form-control'
    - post.pictures.each do |picture|
      = image_tag picture.url, size: '100x100', class: 'image-thumbnail'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  = f.submit class: 'btn btn-primary btn-raised'

app/views/posts/_like.html.slim
/ likes_pathにオプションでクエリパラメータとしてpost_id: post.idを渡している
= link_to likes_path(post_id: post.id), method: :post, class: 'like-button', remote: true do
  = icon 'far', 'heart', class: 'fa-lg'

app/views/posts/_like_area.html.slim
div id="like_area-#{post.id}"
  - if current_user.like?(post)
    = render 'unlike', post: post
  - else
    = render 'like', post: post

app/views/posts/_post.html.slim
.card.mb-5.post id="post-#{post.id}"
  .card-header
    .d-flex.align-items-center
      = image_tag post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
      = post.user.username
      - if current_user&.own?(post)
        .ml-auto
          = link_to post_path(post), class: 'mr-3 delete-button', method: :delete, data: { confirm: '本当に削除しますか？' } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post) , class: 'edit-button' do
            = icon 'far', 'edit', class: 'fa-lg'
      - if current_user && !current_user.own?(post)
        .ml-auto
          = render 'like_area', post: post
  = link_to post_path(post) do
    .swiper-container
      .swiper-wrapper
        - post.pictures.each do |picture|
          .swiper-slide
            = image_tag picture.url, class: 'card-img-top'
      .swiper-pagination
  .card-body
    .card-text
      = post.content

app/views/posts/_search_form.html.slim
= form_with model: search_form, url: search_posts_path, scope: :q, class: 'form-inline my-2 my-lg-0 mr-auto', method: :get, local: true do |f|
  = f.search_field :content, class: 'form-control mr-sm-2', placeholder: '本文'
  = f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

app/views/posts/_thumbnail_post.html.slim
.col-md-4.mb-3
  = link_to post_path(thumbnail_post), class: 'thumbs' do
    = image_tag thumbnail_post.pictures.first.url

app/views/posts/_unlike.html.slim
/ like_path(@like)にdeleteリクエストを送る
= link_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, class: 'unlike-button', remote: true do
  = icon 'fa', 'heart', class: 'fa-lg'

app/views/posts/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-3
      .card
        .card-body
          = render 'form', post: @post

app/views/posts/index.html.slim
.container
  .row
    .col-md-8.col-12
      - if @posts.present?
        = render @posts
      - else
        .text-center.font-weight-bold
          | 投稿がありません
      = paginate @posts
    .col-md-4.col-12
      - if logged_in?
        .profile-box.mb-3
          = image_tag current_user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
          = link_to current_user.username, edit_mypage_account_path
      .users-box
        .card
          .card-header
            | ユーザー
          .card-body
            = render @users
          .card-footer
            = link_to 'すべて見る', users_path

app/views/posts/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-body
          = render 'form', post: @post

app/views/posts/search.html.slim
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        | 検索結果: #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
.post-detail.card
  .image-box
    .swiper-container
      .swiper-wrapper
        - @post.pictures.each do |picture|
          .swiper-slide
            = image_tag picture.url
      .swiper-pagination
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.username
        - if current_user&.own?(@post)
          .ml-auto
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post) do
              = icon 'far', 'edit', class: 'fa-lg'
        - if current_user && !current_user.own?(@post)
          .ml-auto
            = render 'like_area', post: @post
    hr.m-0
    .post-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2
          = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle'
        .col-10
          = simple_format(@post.content)
      hr
      / コメント一覧
      = render 'comments/comments', comments: @comments
    hr.m-0
    .post-comment.p-3
      = render 'comments/form', post: @post, comment: @comment